apiVersion: v2
name: rasa
description: The rasa Helm charts deploy a Rasa Open Source bot. Rasa is an open source machine learning framework for automated text and voice-based conversations.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.7.0"

icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU"

sources:
  - https://github.com/RasaHQ/charts/rasa
  - https://rasa.com/

maintainers:
  - email: hi@rasa.com
    name: RasaHQ

dependencies:
  - name: rasa-common
    repository: file://../rasa-common
    tags:
      - rasa-common
    version: 1.x.x

  - name: postgresql
    version: ~10.3.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install

  - name: redis
    version: ~14.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.install

  - name: rabbitmq
    version: ~8.12.1
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install

  - name: rasa-action-server
    version: ~1.0.0
    repository: file://../rasa-action-server
    condition: rasa-action-server.install

  - name: duckling
    version: ~1.0.0
    repository: file://../duckling
    condition: duckling.install

annotations:
  # See: https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations
  artifacthub.io/changes: |
    - kind: added
      description: Add the rasa chart
