apiVersion: v2
name: rasa-common
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
#
# Version and appVersion should be the same.
version: 1.0.0
appVersion: 1.0.0
description: A Library Helm Chart for grouping common logic between rasa charts.

home: https://github.com/RasaHQ/charts/tree/master/charts/rasa-common
keywords:
  - common
  - template
  - function
  - rasa

icon: icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU

type: library
sources:
  - https://github.com/RasaHQ/helm-charts/rasa-common
  - https://rasa.com/
maintainers:
  - email: contact@rasa.com
    name: Rasa

annotations:
  category: Infrastructure
