apiVersion: v2
name: rasa-common
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
#
# Version and appVersion should be the same.
version: 1.0.2
appVersion: 1.0.2
description: A Library Helm Chart for grouping common logic between rasa charts.

home: https://github.com/RasaHQ/charts/tree/master/charts/rasa-common
keywords:
  - common
  - template
  - function
  - rasa

icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU

type: library
sources:
  - https://github.com/RasaHQ/helm-charts/charts/rasa-common
  - https://rasa.com/

maintainers:
  - email: hi@rasa.com
    name: Rasa

annotations:
  category: Infrastructure
  # See: https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations
  artifacthub.io/changes: |
    - kind: fixed
      description: Issue with default value not being accessed
      links:
        - name: Github Issue
          url: https://github.com/RasaHQ/helm-charts/issues/40
